version: "3"

networks:
  proxy:
    external: true
  internal:
    external: false

services:
  app:
    image: "nginx:1.15.2-alpine"
    volumes:
      - ".:/var/www/html"
      - "./nginx/app-prod.conf:/etc/nginx/conf.d/default.conf"
    labels:
      - traefik.enable=true
      - traefik.backend=app
      - traefik.frontend.rule=Host:www.adoteumpet.com.br
      - traefik.docker.network=proxy
      - traefik.port=80
    networks: 
      - internal
      - proxy
